<?php

namespace Database\Seeders;

use App\Models\Tenant\Accounting\Accountants\Account;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $accounts = [
            [
                'id' => 1,
                'account_code' => '1',
                'classification' => 'ASSET',
                'name' => ['ar' => 'الأصول', 'en' => 'Assets'],
                'activity' => 'OPERATING',
                'parent_id' => null,
                'children' => [2, 13, 16],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 2,
                'account_code' => '11',
                'classification' => 'ASSET',
                'name' => ['ar' => 'الأصول المتداولة', 'en' => 'Current Assets'],
                'activity' => 'OPERATING',
                'parent_id' => 1,
                'children' => [3, 7, 8, 9, 10, 12],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 3,
                'account_code' => '111',
                'classification' => 'ASSET',
                'name' => ['ar' => 'النقد وما يعادله', 'en' => 'Cash and Cash Equivalents'],
                'activity' => 'CASH',
                'parent_id' => 2,
                'children' => [4, 5, 6],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 4,
                'account_code' => '1111',
                'classification' => 'ASSET',
                'name' => ['ar' => 'الخزينة', 'en' => 'Undeposited Funds'],
                'activity' => 'CASH',
                'parent_id' => 3,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => 3,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 5,
                'account_code' => '1112',
                'classification' => 'ASSET',
                'name' => ['ar' => 'المصروفات النثرية', 'en' => 'Petty Cash'],
                'activity' => 'CASH',
                'parent_id' => 3,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => 2,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 6,
                'account_code' => '1113',
                'classification' => 'ASSET',
                'name' => ['ar' => 'الحساب البنكي', 'en' => 'Bank Account'],
                'activity' => 'CASH',
                'parent_id' => 3,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => 1,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 7,
                'account_code' => '112',
                'classification' => 'ASSET',
                'name' => ['ar' => 'العملاء', 'en' => 'Accounts Receivable'],
                'activity' => 'OPERATING',
                'parent_id' => 2,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 8,
                'account_code' => '113',
                'classification' => 'ASSET',
                'name' => ['ar' => 'سلف الموظفين', 'en' => 'Employee Advance'],
                'activity' => 'OPERATING',
                'parent_id' => 2,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 9,
                'account_code' => '114',
                'classification' => 'ASSET',
                'name' => ['ar' => 'مصروفات مدفوعة مقدما', 'en' => 'Prepaid Expenses'],
                'activity' => 'OPERATING',
                'parent_id' => 2,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 10,
                'account_code' => '115',
                'classification' => 'ASSET',
                'name' => ['ar' => 'إدارة المخزون', 'en' => 'Inventory'],
                'activity' => 'INVESTING',
                'parent_id' => 2,
                'children' => [11],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 11,
                'account_code' => '1151',
                'classification' => 'ASSET',
                'name' => ['ar' => 'المستودع الرئيسي', 'en' => 'Primary Warehouse'],
                'activity' => 'OPERATING',
                'parent_id' => 2,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 12,
                'account_code' => '116',
                'classification' => 'ASSET',
                'name' => ['ar' => 'ضريبة مسددة مقدمًا', 'en' => 'Advance Tax'],
                'activity' => 'OPERATING',
                'parent_id' => 2,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 13,
                'account_code' => '12',
                'classification' => 'ASSET',
                'name' => ['ar' => 'الأصول الثابتة', 'en' => 'Fixed Asset'],
                'activity' => 'INVESTING',
                'parent_id' => 1,
                'children' => [14, 15],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 14,
                'account_code' => '121',
                'classification' => 'ASSET',
                'name' => ['ar' => 'أثاث و معدات', 'en' => 'Furniture and Equipment'],
                'activity' => 'INVESTING',
                'parent_id' => 13,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 15,
                'account_code' => '122',
                'classification' => 'ASSET',
                'name' => ['ar' => 'مجمع الإهلاك التراكمي', 'en' => 'Accumulated depreciation'],
                'activity' => 'INVESTING',
                'parent_id' => 13,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 16,
                'account_code' => '13',
                'classification' => 'ASSET',
                'name' => ['ar' => 'الأصول غير المتداولة', 'en' => 'Non-Current Assets'],
                'activity' => 'OPERATING',
                'parent_id' => 1,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 17,
                'account_code' => '2',
                'classification' => 'LIABILITY',
                'name' => ['ar' => 'الإلتزامات', 'en' => 'Liabilities'],
                'activity' => 'OPERATING',
                'parent_id' => null,
                'children' => [18, 30],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 18,
                'account_code' => '21',
                'classification' => 'LIABILITY',
                'name' => ['ar' => 'الإلتزامات المتداولة', 'en' => 'Current Liabilities'],
                'activity' => 'OPERATING',
                'parent_id' => 17,
                'children' => [19, 20, 21, 22, 23, 24, 25, 26, 28, 29],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 19,
                'account_code' => '211',
                'classification' => 'LIABILITY',
                'name' => ['ar' => 'الموردين', 'en' => 'Accounts Payable'],
                'activity' => 'OPERATING',
                'parent_id' => 18,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 20,
                'account_code' => '2110',
                'classification' => 'LIABILITY',
                'name' => ['ar' => 'ضريبة القيمة المضافة على الحسابات الدائنة', 'en' => 'VAT Payable'],
                'activity' => 'OPERATING',
                'parent_id' => 18,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 21,
                'account_code' => '2111',
                'classification' => 'LIABILITY',
                'name' => ['ar' => 'زكاة مستحقة الدفع', 'en' => 'Zakat Payable'],
                'activity' => 'OPERATING',
                'parent_id' => 18,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 22,
                'account_code' => '212',
                'classification' => 'LIABILITY',
                'name' => ['ar' => 'إيراد غير مكتسب', 'en' => 'Unearned Revenue'],
                'activity' => 'OPERATING',
                'parent_id' => 18,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 23,
                'account_code' => '213',
                'classification' => 'LIABILITY',
                'name' => ['ar' => 'تعديلات الرصيد الافتتاحي', 'en' => 'Opening Balance Adjustments'],
                'activity' => 'FINANCING',
                'parent_id' => 18,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 24,
                'account_code' => '214',
                'classification' => 'LIABILITY',
                'name' => ['ar' => 'رواتب مستحقة غير مدفوعة', 'en' => 'Payroll Payable'],
                'activity' => 'OPERATING',
                'parent_id' => 18,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 25,
                'account_code' => '215',
                'classification' => 'LIABILITY',
                'name' => ['ar' => 'قرض من المالك', 'en' => 'Loan from Owner'],
                'activity' => 'FINANCING',
                'parent_id' => 18,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 26,
                'account_code' => '216',
                'classification' => 'LIABILITY',
                'name' => ['ar' => 'تعويضات الموظفين', 'en' => 'Employee Reimbursements'],
                'activity' => 'OPERATING',
                'parent_id' => 18,
                'children' => [27],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 28,
                'account_code' => '218',
                'classification' => 'LIABILITY',
                'name' => ['ar' => 'القيمة المضافة', 'en' => 'VAT'],
                'activity' => 'OPERATING',
                'parent_id' => 18,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 29,
                'account_code' => '219',
                'classification' => 'LIABILITY',
                'name' => ['ar' => 'ضريبة السلع الانتقائية المستحقة', 'en' => 'Excise Tax Payable'],
                'activity' => 'OPERATING',
                'parent_id' => 18,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 30,
                'account_code' => '22',
                'classification' => 'LIABILITY',
                'name' => ['ar' => 'الإلتزامات غير المتداولة', 'en' => 'Non-Current Liabilities'],
                'activity' => 'OPERATING',
                'parent_id' => 2,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 31,
                'account_code' => '3',
                'classification' => 'EQUITY',
                'name' => ['ar' => 'حقوق الملكية', 'en' => 'Equity'],
                'activity' => 'FINANCING',
                'parent_id' => null,
                'children' => [32, 34, 37, 39, 41],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 32,
                'account_code' => '31',
                'classification' => 'EQUITY',
                'name' => ['ar' => 'حقوق ملكية من رصيد إفتتاحي', 'en' => 'Opening Balance Equity'],
                'activity' => 'INVESTING',
                'parent_id' => 31,
                'children' => [33],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 33,
                'account_code' => '311',
                'classification' => 'EQUITY',
                'name' => ['ar' => 'إزاحة الرصيد الافتتاحي', 'en' => 'Opening Balance Offset'],
                'activity' => 'FINANCING',
                'parent_id' => 32,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 34,
                'account_code' => '32',
                'classification' => 'EQUITY',
                'name' => ['ar' => 'حقوق ملكية المالك', 'en' => 'Owner\'s Equity'],
                'activity' => 'INVESTING',
                'parent_id' => 31,
                'children' => [35, 36],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 35,
                'account_code' => '321',
                'classification' => 'EQUITY',
                'name' => ['ar' => 'حقوق ملكية المالك', 'en' => 'Owner\'s Equity'],
                'activity' => 'FINANCING',
                'parent_id' => 34,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 36,
                'account_code' => '322',
                'classification' => 'EQUITY',
                'name' => ['ar' => 'المسحوبات', 'en' => 'Drawings'],
                'activity' => 'FINANCING',
                'parent_id' => 34,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 37,
                'account_code' => '33',
                'classification' => 'EQUITY',
                'name' => ['ar' => 'الأرباح المحتجزة', 'en' => 'Retained Earnings'],
                'activity' => 'OPERATING',
                'parent_id' => 31,
                'children' => [38],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 38,
                'account_code' => '331',
                'classification' => 'EQUITY',
                'name' => ['ar' => 'الأرباح المحتجزة', 'en' => 'Retained Earnings'],
                'activity' => 'OPERATING',
                'parent_id' => 37,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 39,
                'account_code' => '34',
                'classification' => 'EQUITY',
                'name' => ['ar' => 'الدخل الشامل الآخر المتراكم', 'en' => 'Acc. Other Comprehensive Income'],
                'activity' => 'OPERATING',
                'parent_id' => 31,
                'children' => [40],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 40,
                'account_code' => '341',
                'classification' => 'EQUITY',
                'name' => ['ar' => 'أرباح و خسائر غير محققة', 'en' => 'Unrealized gains and losses'],
                'activity' => 'OPERATING',
                'parent_id' => 39,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 41,
                'account_code' => '35',
                'classification' => 'EQUITY',
                'name' => ['ar' => 'رأس المال الإضافي المدفوع', 'en' => 'Paid-in Capital'],
                'activity' => 'INVESTING',
                'parent_id' => 31,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 42,
                'account_code' => '4',
                'classification' => 'REVENUE',
                'name' => ['ar' => 'الإيراد', 'en' => 'Revenue'],
                'activity' => 'OPERATING',
                'parent_id' => null,
                'children' => [43, 50],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 43,
                'account_code' => '41',
                'classification' => 'REVENUE',
                'name' => ['ar' => 'دخل', 'en' => 'Income'],
                'activity' => 'OPERATING',
                'parent_id' => 42,
                'children' => [44, 45, 46, 47, 48, 49],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 44,
                'account_code' => '411',
                'classification' => 'REVENUE',
                'name' => ['ar' => 'مبيعات', 'en' => 'Sales'],
                'activity' => 'OPERATING',
                'parent_id' => 43,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 45,
                'account_code' => '412',
                'classification' => 'REVENUE',
                'name' => ['ar' => 'الايرادات من الفائدة', 'en' => 'Interest Income'],
                'activity' => 'OPERATING',
                'parent_id' => 43,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 46,
                'account_code' => '413',
                'classification' => 'REVENUE',
                'name' => ['ar' => 'دخل الرسوم المتأخرة', 'en' => 'Late Fee Income'],
                'activity' => 'OPERATING',
                'parent_id' => 43,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 47,
                'account_code' => '414',
                'classification' => 'REVENUE',
                'name' => ['ar' => 'رسوم الشحن', 'en' => 'Shipping Charge'],
                'activity' => 'OPERATING',
                'parent_id' => 43,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 48,
                'account_code' => '415',
                'classification' => 'REVENUE',
                'name' => ['ar' => 'رسوم أخرى', 'en' => 'Other Charges'],
                'activity' => 'OPERATING',
                'parent_id' => 43,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 49,
                'account_code' => '416',
                'classification' => 'REVENUE',
                'name' => ['ar' => 'خصم', 'en' => 'Discount'],
                'activity' => 'OPERATING',
                'parent_id' => 43,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 50,
                'account_code' => '42',
                'classification' => 'REVENUE',
                'name' => ['ar' => 'إيرادات أخرى', 'en' => 'Other Income'],
                'activity' => 'OPERATING',
                'parent_id' => 42,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 51,
                'account_code' => '5',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'المصروفات', 'en' => 'Expenses'],
                'activity' => 'OPERATING',
                'parent_id' => null,
                'children' => [52, 54, 73],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 52,
                'account_code' => '51',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'تكاليف المبيعات', 'en' => 'Cost of Sales'],
                'activity' => 'OPERATING',
                'parent_id' => 51,
                'children' => [53],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 53,
                'account_code' => '511',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'تكلفة البضائع المباعة', 'en' => 'Cost of Goods Sold'],
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 54,
                'account_code' => '52',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'المصروفات التشغيلية', 'en' => 'Operating Expenses'],
                'activity' => 'OPERATING',
                'parent_id' => 51,
                'children' => [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 55,
                'account_code' => '521',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'اللوازم المكتبية', 'en' => 'Office Supplies'],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 56,
                'account_code' => '5210',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'مصروف الإيجار', 'en' => 'Rent Expense'],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 57,
                'account_code' => '5211',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'مصروفات متعلقة بنظافة المباني', 'en' => 'Janitorial Expense'],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 58,
                'account_code' => '5212',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'أجرة البريد', 'en' => 'Postage'],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 59,
                'account_code' => '5213',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'دين معدوم', 'en' => 'Bad Debt'],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 60,
                'account_code' => '5214',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'الطباعة والقرطاسية', 'en' => 'Printing and Stationery'],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 61,
                'account_code' => '5215',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'رواتب وأجور الموظفين', 'en' => 'Salaries and Employee Wages'],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 62,
                'account_code' => '5216',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'مصاريف مستشارية', 'en' => 'Consultant Expense'],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 63,
                'account_code' => '5217',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'الإصلاحات والصيانة', 'en' => 'Repairs and Maintenance'],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 64,
                'account_code' => '5218',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'المصاريف الآخرى', 'en' => 'Other Expenses'],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => true,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 65,
                'account_code' => '522',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'السكن', 'en' => 'Lodging'],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 66,
                'account_code' => '523',
                'classification' => 'EXPENSE',
                'name' => ['ar' => 'الإعلان والتسويق', 'en' => 'Advertising And Marketing'],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 67,
                'account_code' => '524',
                'classification' => 'EXPENSE',
                'name' => [ 'ar' => 'الرسوم الإضافية البنكية والمصاريف', 'en' => 'Bank Fees and Charges' ],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 68,
                'account_code' => '525',
                'classification' => 'EXPENSE',
                'name' => [ 'ar' => 'رسوم بطاقات الائتمان', 'en' => 'Credit Card Charges' ],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 69,
                'account_code' => '526',
                'classification' => 'EXPENSE',
                'name' => [ 'ar' => 'تكاليف السفر', 'en' => 'Travel Expense' ],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => true,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 70,
                'account_code' => '527',
                'classification' => 'EXPENSE',
                'name' => [ 'ar' => 'مصروفات الهاتف', 'en' => 'Telephone Expense' ],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => true,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 71,
                'account_code' => '528',
                'classification' => 'EXPENSE',
                'name' => [ 'ar' => 'مصروفات المركبات', 'en' => 'Vehicle Expense' ],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => true,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 72,
                'account_code' => '529',
                'classification' => 'EXPENSE',
                'name' => [ 'ar' => 'البرامج والأدوات', 'en' => 'Software and Tools' ],
                'activity' => 'OPERATING',
                'parent_id' => 54,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 73,
                'account_code' => '53',
                'classification' => 'EXPENSE',
                'name' => [ 'ar' => 'المصروفات الغير التشغيلية', 'en' => 'Non-Operating Expenses' ],
                'activity' => 'OPERATING',
                'parent_id' => 51,
                'children' => [74, 75, 76, 77],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 74,
                'account_code' => '531',
                'classification' => 'EXPENSE',
                'name' => [ 'ar' => 'خسارة أو ربح في صرف العملات', 'en' => 'Exchange Gain or Loss' ],
                'activity' => 'OPERATING',
                'parent_id' => 73,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 75,
                'account_code' => '532',
                'classification' => 'EXPENSE',
                'name' => [ 'ar' => 'غير مصنف', 'en' => 'Uncategorized' ],
                'activity' => 'OPERATING',
                'parent_id' => 73,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 76,
                'account_code' => '533',
                'classification' => 'EXPENSE',
                'name' => [ 'ar' => 'الوجبات والترفيه', 'en' => 'Meals and Entertainment' ],
                'activity' => 'OPERATING',
                'parent_id' => 73,
                'children' => [],
                'show_in_expense_claims' => true,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 77,
                'account_code' => '534',
                'classification' => 'EXPENSE',
                'name' => [ 'ar' => 'مصاريف الإهلاك', 'en' => 'Depreciation Expense' ],
                'activity' => 'OPERATING',
                'parent_id' => 73,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
        ];

        DB::table('accounts')->insert($accounts);
    }
}
