<?php

namespace Database\Seeders;

use App\Models\Tenant\Accountants\Account;
use Illuminate\Database\Seeder;

class AccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $accountsData = [
            [
                'id' => 1,
                'account_code' => '1',
                'classification' => 'ASSET',
                'name_ar' => 'الأصول',
                'name_en' => 'Assets',
                'activity' => 'OPERATING',
                'parent_id' => null,
                'children' => [2, 13, 16],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 2,
                'account_code' => '11',
                'classification' => 'ASSET',
                'name_ar' => 'الأصول المتداولة',
                'name_en' => 'Current Assets',
                'activity' => 'OPERATING',
                'parent_id' => 1,
                'children' => [3, 7, 8, 9, 10, 12],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 3,
                'account_code' => '111',
                'classification' => 'ASSET',
                'name_ar' => 'النقد وما يعادله',
                'name_en' => 'Cash and Cash Equivalents',
                'activity' => 'CASH',
                'parent_id' => 11,
                'children' => [4, 5, 6],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 4,
                'account_code' => '1111',
                'classification' => 'ASSET',
                'name_ar' => 'الخزينة',
                'name_en' => 'Undeposited Funds',
                'activity' => 'CASH',
                'parent_id' => 111,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => 3,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 5,
                'account_code' => '1112',
                'classification' => 'ASSET',
                'name_ar' => 'المصروفات النثرية',
                'name_en' => 'Petty Cash',
                'activity' => 'CASH',
                'parent_id' => 111,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => 2,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 6,
                'account_code' => '1113',
                'classification' => 'ASSET',
                'name_ar' => 'الحساب البنكي',
                'name_en' => 'Bank Account',
                'activity' => 'CASH',
                'parent_id' => 111,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => 1,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 7,
                'account_code' => '112',
                'classification' => 'ASSET',
                'name_ar' => 'العملاء',
                'name_en' => 'Accounts Receivable',
                'activity' => 'OPERATING',
                'parent_id' => 11,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 8,
                'account_code' => '113',
                'classification' => 'ASSET',
                'name_ar' => 'سلف الموظفين',
                'name_en' => 'Employee Advance',
                'activity' => 'OPERATING',
                'parent_id' => 11,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 9,
                'account_code' => '114',
                'classification' => 'ASSET',
                'name_ar' => 'مصروفات مدفوعة مقدما',
                'name_en' => 'Prepaid Expenses',
                'activity' => 'OPERATING',
                'parent_id' => 11,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 10,
                'account_code' => '115',
                'classification' => 'ASSET',
                'name_ar' => 'إدارة المخزون',
                'name_en' => 'Inventory',
                'activity' => 'INVESTING',
                'parent_id' => 11,
                'children' => [11],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 11,
                'account_code' => '1151',
                'classification' => 'ASSET',
                'name_ar' => 'المستودع الرئيسي',
                'name_en' => 'Primary Warehouse',
                'activity' => 'OPERATING',
                'parent_id' => 115,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 12,
                'account_code' => '116',
                'classification' => 'ASSET',
                'name_ar' => 'ضريبة مسددة مقدمًا',
                'name_en' => 'Advance Tax',
                'activity' => 'OPERATING',
                'parent_id' => 11,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 13,
                'account_code' => '12',
                'classification' => 'ASSET',
                'name_ar' => 'الأصول الثابتة',
                'name_en' => 'Fixed Asset',
                'activity' => 'INVESTING',
                'parent_id' => 1,
                'children' => [14, 15],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 14,
                'account_code' => '121',
                'classification' => 'ASSET',
                'name_ar' => 'أثاث و معدات',
                'name_en' => 'Furniture and Equipment',
                'activity' => 'INVESTING',
                'parent_id' => 12,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 15,
                'account_code' => '122',
                'classification' => 'ASSET',
                'name_ar' => 'مجمع الإهلاك التراكمي',
                'name_en' => 'Accumulated depreciation',
                'activity' => 'INVESTING',
                'parent_id' => 12,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 16,
                'account_code' => '13',
                'classification' => 'ASSET',
                'name_ar' => 'الأصول غير المتداولة',
                'name_en' => 'Non-Current Assets',
                'activity' => 'OPERATING',
                'parent_id' => 1,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 17,
                'account_code' => '2',
                'classification' => 'LIABILITY',
                'name_ar' => 'الإلتزامات',
                'name_en' => 'Liabilities',
                'activity' => 'OPERATING',
                'parent_id' => null,
                'children' => [18, 30],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 18,
                'account_code' => '21',
                'classification' => 'LIABILITY',
                'name_ar' => 'الإلتزامات المتداولة',
                'name_en' => 'Current Liabilities',
                'activity' => 'OPERATING',
                'parent_id' => 2,
                'children' => [19, 20, 21, 22, 23, 24, 25, 26, 28, 29],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 19,
                'account_code' => '211',
                'classification' => 'LIABILITY',
                'name_ar' => 'الموردين',
                'name_en' => 'Accounts Payable',
                'activity' => 'OPERATING',
                'parent_id' => 21,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 20,
                'account_code' => '2110',
                'classification' => 'LIABILITY',
                'name_ar' => 'ضريبة القيمة المضافة على الحسابات الدائنة',
                'name_en' => 'VAT Payable',
                'activity' => 'OPERATING',
                'parent_id' => 21,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 21,
                'account_code' => '2111',
                'classification' => 'LIABILITY',
                'name_ar' => 'زكاة مستحقة الدفع',
                'name_en' => 'Zakat Payable',
                'activity' => 'OPERATING',
                'parent_id' => 21,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 22,
                'account_code' => '212',
                'classification' => 'LIABILITY',
                'name_ar' => 'إيراد غير مكتسب',
                'name_en' => 'Unearned Revenue',
                'activity' => 'OPERATING',
                'parent_id' => 21,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 23,
                'account_code' => '213',
                'classification' => 'LIABILITY',
                'name_ar' => 'تعديلات الرصيد الافتتاحي',
                'name_en' => 'Opening Balance Adjustments',
                'activity' => 'FINANCING',
                'parent_id' => 21,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 24,
                'account_code' => '214',
                'classification' => 'LIABILITY',
                'name_ar' => 'رواتب مستحقة غير مدفوعة',
                'name_en' => 'Payroll Payable',
                'activity' => 'OPERATING',
                'parent_id' => 21,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 25,
                'account_code' => '215',
                'classification' => 'LIABILITY',
                'name_ar' => 'قرض من المالك',
                'name_en' => 'Loan from Owner',
                'activity' => 'FINANCING',
                'parent_id' => 21,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 26,
                'account_code' => '216',
                'classification' => 'LIABILITY',
                'name_ar' => 'تعويضات الموظفين',
                'name_en' => 'Employee Reimbursements',
                'activity' => 'OPERATING',
                'parent_id' => 21,
                'children' => [27],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 28,
                'account_code' => '218',
                'classification' => 'LIABILITY',
                'name_ar' => 'القيمة المضافة',
                'name_en' => 'VAT',
                'activity' => 'OPERATING',
                'parent_id' => 21,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 29,
                'account_code' => '219',
                'classification' => 'LIABILITY',
                'name_ar' => 'ضريبة السلع الانتقائية المستحقة',
                'name_en' => 'Excise Tax Payable',
                'activity' => 'OPERATING',
                'parent_id' => 21,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 30,
                'account_code' => '22',
                'classification' => 'LIABILITY',
                'name_ar' => 'الإلتزامات غير المتداولة',
                'name_en' => 'Non-Current Liabilities',
                'activity' => 'OPERATING',
                'parent_id' => 2,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 31,
                'account_code' => '3',
                'classification' => 'EQUITY',
                'name_ar' => 'حقوق الملكية',
                'name_en' => 'Equity',
                'activity' => 'FINANCING',
                'parent_id' => null,
                'children' => [32, 34, 37, 39, 41],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 32,
                'account_code' => '31',
                'classification' => 'EQUITY',
                'name_ar' => 'حقوق ملكية من رصيد إفتتاحي',
                'name_en' => 'Opening Balance Equity',
                'activity' => 'INVESTING',
                'parent_id' => 3,
                'children' => [33],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 33,
                'account_code' => '311',
                'classification' => 'EQUITY',
                'name_ar' => 'إزاحة الرصيد الافتتاحي',
                'name_en' => 'Opening Balance Offset',
                'activity' => 'FINANCING',
                'parent_id' => 31,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 34,
                'account_code' => '32',
                'classification' => 'EQUITY',
                'name_ar' => 'حقوق ملكية المالك',
                'name_en' => 'Owner\'s Equity',
                'activity' => 'INVESTING',
                'parent_id' => 3,
                'children' => [35, 36],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 35,
                'account_code' => '321',
                'classification' => 'EQUITY',
                'name_ar' => 'حقوق ملكية المالك',
                'name_en' => 'Owner\'s Equity',
                'activity' => 'FINANCING',
                'parent_id' => 32,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 36,
                'account_code' => '322',
                'classification' => 'EQUITY',
                'name_ar' => 'المسحوبات',
                'name_en' => 'Drawings',
                'activity' => 'FINANCING',
                'parent_id' => 32,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => true,
            ],
            [
                'id' => 37,
                'account_code' => '33',
                'classification' => 'EQUITY',
                'name_ar' => 'الأرباح المحتجزة',
                'name_en' => 'Retained Earnings',
                'activity' => 'OPERATING',
                'parent_id' => 3,
                'children' => [38],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 38,
                'account_code' => '331',
                'classification' => 'EQUITY',
                'name_ar' => 'الأرباح المحتجزة',
                'name_en' => 'Retained Earnings',
                'activity' => 'OPERATING',
                'parent_id' => 33,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 39,
                'account_code' => '34',
                'classification' => 'EQUITY',
                'name_ar' => 'الدخل الشامل الآخر المتراكم',
                'name_en' => 'Acc. Other Comprehensive Income',
                'activity' => 'OPERATING',
                'parent_id' => 3,
                'children' => [40],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 40,
                'account_code' => '341',
                'classification' => 'EQUITY',
                'name_ar' => 'أرباح و خسائر غير محققة',
                'name_en' => 'Unrealized gains and losses',
                'activity' => 'OPERATING',
                'parent_id' => 34,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 41,
                'account_code' => '35',
                'classification' => 'EQUITY',
                'name_ar' => 'رأس المال الإضافي المدفوع',
                'name_en' => 'Paid-in Capital',
                'activity' => 'INVESTING',
                'parent_id' => 3,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 42,
                'account_code' => '4',
                'classification' => 'REVENUE',
                'name_ar' => 'الإيراد',
                'name_en' => 'Revenue',
                'activity' => 'OPERATING',
                'parent_id' => null,
                'children' => [43, 50],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 43,
                'account_code' => '41',
                'classification' => 'REVENUE',
                'name_ar' => 'دخل',
                'name_en' => 'Income',
                'activity' => 'OPERATING',
                'parent_id' => 4,
                'children' => [44, 45, 46, 47, 48, 49],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 44,
                'account_code' => '411',
                'classification' => 'REVENUE',
                'name_ar' => 'مبيعات',
                'name_en' => 'Sales',
                'activity' => 'OPERATING',
                'parent_id' => 41,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 45,
                'account_code' => '412',
                'classification' => 'REVENUE',
                'name_ar' => 'الايرادات من الفائدة',
                'name_en' => 'Interest Income',
                'activity' => 'OPERATING',
                'parent_id' => 41,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 46,
                'account_code' => '413',
                'classification' => 'REVENUE',
                'name_ar' => 'دخل الرسوم المتأخرة',
                'name_en' => 'Late Fee Income',
                'activity' => 'OPERATING',
                'parent_id' => 41,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 47,
                'account_code' => '414',
                'classification' => 'REVENUE',
                'name_ar' => 'رسوم الشحن',
                'name_en' => 'Shipping Charge',
                'activity' => 'OPERATING',
                'parent_id' => 41,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 48,
                'account_code' => '415',
                'classification' => 'REVENUE',
                'name_ar' => 'رسوم أخرى',
                'name_en' => 'Other Charges',
                'activity' => 'OPERATING',
                'parent_id' => 41,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 49,
                'account_code' => '416',
                'classification' => 'REVENUE',
                'name_ar' => 'خصم',
                'name_en' => 'Discount',
                'activity' => 'OPERATING',
                'parent_id' => 41,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 50,
                'account_code' => '42',
                'classification' => 'REVENUE',
                'name_ar' => 'إيرادات أخرى',
                'name_en' => 'Other Income',
                'activity' => 'OPERATING',
                'parent_id' => 4,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 51,
                'account_code' => '5',
                'classification' => 'EXPENSE',
                'name_ar' => 'المصروفات',
                'name_en' => 'Expenses',
                'activity' => 'OPERATING',
                'parent_id' => null,
                'children' => [52, 54, 73],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 52,
                'account_code' => '51',
                'classification' => 'EXPENSE',
                'name_ar' => 'تكاليف المبيعات',
                'name_en' => 'Cost of Sales',
                'activity' => 'OPERATING',
                'parent_id' => 5,
                'children' => [53],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 53,
                'account_code' => '511',
                'classification' => 'EXPENSE',
                'name_ar' => 'تكلفة البضائع المباعة',
                'name_en' => 'Cost of Goods Sold',
                'activity' => 'OPERATING',
                'parent_id' => 51,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 54,
                'account_code' => '52',
                'classification' => 'EXPENSE',
                'name_ar' => 'المصروفات التشغيلية',
                'name_en' => 'Operating Expenses',
                'activity' => 'OPERATING',
                'parent_id' => 5,
                'children' => [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 55,
                'account_code' => '521',
                'classification' => 'EXPENSE',
                'name_ar' => 'اللوازم المكتبية',
                'name_en' => 'Office Supplies',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 56,
                'account_code' => '5210',
                'classification' => 'EXPENSE',
                'name_ar' => 'مصروف الإيجار',
                'name_en' => 'Rent Expense',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 57,
                'account_code' => '5211',
                'classification' => 'EXPENSE',
                'name_ar' => 'مصروفات متعلقة بنظافة المباني',
                'name_en' => 'Janitorial Expense',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 58,
                'account_code' => '5212',
                'classification' => 'EXPENSE',
                'name_ar' => 'أجرة البريد',
                'name_en' => 'Postage',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 59,
                'account_code' => '5213',
                'classification' => 'EXPENSE',
                'name_ar' => 'دين معدوم',
                'name_en' => 'Bad Debt',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 60,
                'account_code' => '5214',
                'classification' => 'EXPENSE',
                'name_ar' => 'الطباعة والقرطاسية',
                'name_en' => 'Printing and Stationery',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 61,
                'account_code' => '5215',
                'classification' => 'EXPENSE',
                'name_ar' => 'رواتب وأجور الموظفين',
                'name_en' => 'Salaries and Employee Wages',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 62,
                'account_code' => '5216',
                'classification' => 'EXPENSE',
                'name_ar' => 'مصاريف مستشارية',
                'name_en' => 'Consultant Expense',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 63,
                'account_code' => '5217',
                'classification' => 'EXPENSE',
                'name_ar' => 'الإصلاحات والصيانة',
                'name_en' => 'Repairs and Maintenance',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 64,
                'account_code' => '5218',
                'classification' => 'EXPENSE',
                'name_ar' => 'المصاريف الآخرى',
                'name_en' => 'Other Expenses',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => true,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 65,
                'account_code' => '522',
                'classification' => 'EXPENSE',
                'name_ar' => 'السكن',
                'name_en' => 'Lodging',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 66,
                'account_code' => '523',
                'classification' => 'EXPENSE',
                'name_ar' => 'الإعلان والتسويق',
                'name_en' => 'Advertising And Marketing',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 67,
                'account_code' => '524',
                'classification' => 'EXPENSE',
                'name_ar' => 'الرسوم الإضافية البنكية والمصاريف',
                'name_en' => 'Bank Fees and Charges',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 68,
                'account_code' => '525',
                'classification' => 'EXPENSE',
                'name_ar' => 'رسوم بطاقات الائتمان',
                'name_en' => 'Credit Card Charges',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 69,
                'account_code' => '526',
                'classification' => 'EXPENSE',
                'name_ar' => 'تكاليف السفر',
                'name_en' => 'Travel Expense',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => true,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 70,
                'account_code' => '527',
                'classification' => 'EXPENSE',
                'name_ar' => 'مصروفات الهاتف',
                'name_en' => 'Telephone Expense',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => true,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 71,
                'account_code' => '528',
                'classification' => 'EXPENSE',
                'name_ar' => 'مصروفات المركبات',
                'name_en' => 'Vehicle Expense',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => true,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 72,
                'account_code' => '529',
                'classification' => 'EXPENSE',
                'name_ar' => 'البرامج والأدوات',
                'name_en' => 'Software and Tools',
                'activity' => 'OPERATING',
                'parent_id' => 52,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 73,
                'account_code' => '53',
                'classification' => 'EXPENSE',
                'name_ar' => 'المصروفات الغير التشغيلية',
                'name_en' => 'Non-Operating Expenses',
                'activity' => 'OPERATING',
                'parent_id' => 5,
                'children' => [74, 75, 76, 77],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 74,
                'account_code' => '531',
                'classification' => 'EXPENSE',
                'name_ar' => 'خسارة أو ربح في صرف العملات',
                'name_en' => 'Exchange Gain or Loss',
                'activity' => 'OPERATING',
                'parent_id' => 53,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 75,
                'account_code' => '532',
                'classification' => 'EXPENSE',
                'name_ar' => 'غير مصنف',
                'name_en' => 'Uncategorized',
                'activity' => 'OPERATING',
                'parent_id' => 53,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 76,
                'account_code' => '533',
                'classification' => 'EXPENSE',
                'name_ar' => 'الوجبات والترفيه',
                'name_en' => 'Meals and Entertainment',
                'activity' => 'OPERATING',
                'parent_id' => 53,
                'children' => [],
                'show_in_expense_claims' => true,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
            [
                'id' => 77,
                'account_code' => '534',
                'classification' => 'EXPENSE',
                'name_ar' => 'مصاريف الإهلاك',
                'name_en' => 'Depreciation Expense',
                'activity' => 'OPERATING',
                'parent_id' => 53,
                'children' => [],
                'show_in_expense_claims' => false,
                'bank_account_id' => null,
                'is_locked' => true,
                'lock_reason' => 'هذا الحساب مقيد لأنه خاص بنظام مصدقة.',
                'is_system' => true,
                'is_payment_enabled' => false,
            ],
        ];

        $createdAccounts = [];

        foreach ($accountsData as $accountData) {
            $parentId = null;
            if ($accountData['parent_id'] !== null) {
                $parentId = $createdAccounts[$accountData['parent_id']]->id ?? null;
            }

            $account = Account::create([
                'account_code' => $accountData['account_code'],
                'classification' => $accountData['classification'],
                'name_ar' => $accountData['name_ar'],
                'name_en' => $accountData['name_en'],
                'activity' => $accountData['activity'],
                'parent_id' => $parentId,
                'show_in_expense_claims' => $accountData['show_in_expense_claims'],
                'is_locked' => $accountData['is_locked'],
                'lock_reason' => $accountData['lock_reason'],
                'is_system' => $accountData['is_system'],
                'is_payment_enabled' => $accountData['is_payment_enabled'],
            ]);

            $createdAccounts[$accountData['account_code']] = $account;
        }
    }
}
