<?php

namespace App\Enums;

enum CountryType: string
{
    case AFGHANISTAN = 'AFGHANISTAN';
    case ALBANIA = 'ALBANIA';
    case ALGERIA = 'ALGERIA';
    case ANDORRA = 'ANDORRA';
    case ANGOLA = 'ANGOLA';
    case ANTIGUA_AND_BARBUDA = 'ANTIGUA_AND_BARBUDA';
    case ARGENTINA = 'ARGENTINA';
    case ARMENIA = 'ARMENIA';
    case AUSTRALIA = 'AUSTRALIA';
    case AUSTRIA = 'AUSTRIA';
    case AZERBAIJAN = 'AZERBAIJAN';
    case BAHAMAS = 'BAHAMAS';
    case BAHRAIN = 'BAHRAIN';
    case BANGLADESH = 'BANGLADESH';
    case BARBADOS = 'BARBADOS';
    case BELARUS = 'BELARUS';
    case BELGIUM = 'BELGIUM';
    case BELIZE = 'BELIZE';
    case BENIN = 'BENIN';
    case BHUTAN = 'BHUTAN';
    case BOLIVIA = 'BOLIVIA';
    case BOSNIA_AND_HERZEGOVINA = 'BOSNIA_AND_HERZEGOVINA';
    case BOTSWANA = 'BOTSWANA';
    case BRAZIL = 'BRAZIL';
    case BRUNEI = 'BRUNEI';
    case BULGARIA = 'BULGARIA';
    case BURKINA_FASO = 'BURKINA_FASO';
    case BURUNDI = 'BURUNDI';
    case CAMBODIA = 'CAMBODIA';
    case CAMEROON = 'CAMEROON';
    case CANADA = 'CANADA';
    case CAPE_VERDE = 'CAPE_VERDE';
    case CENTRAL_AFRICAN_REPUBLIC = 'CENTRAL_AFRICAN_REPUBLIC';
    case CHAD = 'CHAD';
    case CHILE = 'CHILE';
    case CHINA = 'CHINA';
    case COLOMBIA = 'COLOMBIA';
    case COMOROS = 'COMOROS';
    case CONGO = 'CONGO';
    case COSTA_RICA = 'COSTA_RICA';
    case CROATIA = 'CROATIA';
    case CUBA = 'CUBA';
    case CYPRUS = 'CYPRUS';
    case CZECHIA = 'CZECHIA';
    case DENMARK = 'DENMARK';
    case DJIBOUTI = 'DJIBOUTI';
    case DOMINICA = 'DOMINICA';
    case ECUADOR = 'ECUADOR';
    case EGYPT = 'EGYPT';
    case EL_SALVADOR = 'EL_SALVADOR';
    case ESTONIA = 'ESTONIA';
    case ETHIOPIA = 'ETHIOPIA';
    case FIJI = 'FIJI';
    case FINLAND = 'FINLAND';
    case FRANCE = 'FRANCE';
    case GERMANY = 'GERMANY';
    case GHANA = 'GHANA';
    case GREECE = 'GREECE';
    case GUATEMALA = 'GUATEMALA';
    case HAITI = 'HAITI';
    case HONDURAS = 'HONDURAS';
    case HUNGARY = 'HUNGARY';
    case ICELAND = 'ICELAND';
    case INDIA = 'INDIA';
    case INDONESIA = 'INDONESIA';
    case IRAN = 'IRAN';
    case IRAQ = 'IRAQ';
    case IRELAND = 'IRELAND';
    case ISRAEL = 'ISRAEL';
    case ITALY = 'ITALY';
    case JAMAICA = 'JAMAICA';
    case JAPAN = 'JAPAN';
    case JORDAN = 'JORDAN';
    case KAZAKHSTAN = 'KAZAKHSTAN';
    case KENYA = 'KENYA';
    case KUWAIT = 'KUWAIT';
    case LATVIA = 'LATVIA';
    case LEBANON = 'LEBANON';
    case LIBYA = 'LIBYA';
    case LUXEMBOURG = 'LUXEMBOURG';
    case MADAGASCAR = 'MADAGASCAR';
    case MALAYSIA = 'MALAYSIA';
    case MEXICO = 'MEXICO';
    case MOROCCO = 'MOROCCO';
    case NETHERLANDS = 'NETHERLANDS';
    case NEW_ZEALAND = 'NEW_ZEALAND';
    case NIGERIA = 'NIGERIA';
    case NORWAY = 'NORWAY';
    case PAKISTAN = 'PAKISTAN';
    case PERU = 'PERU';
    case PHILIPPINES = 'PHILIPPINES';
    case POLAND = 'POLAND';
    case PORTUGAL = 'PORTUGAL';
    case QATAR = 'QATAR';
    case ROMANIA = 'ROMANIA';
    case RUSSIA = 'RUSSIA';
    case SAUDI_ARABIA = 'SAUDI_ARABIA';
    case SINGAPORE = 'SINGAPORE';
    case SOUTH_AFRICA = 'SOUTH_AFRICA';
    case SOUTH_KOREA = 'SOUTH_KOREA';
    case SPAIN = 'SPAIN';
    case SRI_LANKA = 'SRI_LANKA';
    case SWEDEN = 'SWEDEN';
    case SWITZERLAND = 'SWITZERLAND';
    case THAILAND = 'THAILAND';
    case TUNISIA = 'TUNISIA';
    case TURKEY = 'TURKEY';
    case UAE = 'UAE';
    case UK = 'UK';
    case UKRAINE = 'UKRAINE';
    case USA = 'USA';
    case VIETNAM = 'VIETNAM';
    case ZIMBABWE = 'ZIMBABWE';

    public static function options(): array
    {
        return array_map(fn($case) => [
            'value' => $case->value,
            'label' => match ($case) {
                self::AFGHANISTAN => 'أفغانستان',
                self::ALBANIA => 'ألبانيا',
                self::ALGERIA => 'الجزائر',
                self::ANDORRA => 'أندورا',
                self::ANGOLA => 'أنغولا',
                self::ANTIGUA_AND_BARBUDA => 'أنتيغوا وبربودا',
                self::ARGENTINA => 'الأرجنتين',
                self::ARMENIA => 'أرمينيا',
                self::AUSTRALIA => 'أستراليا',
                self::AUSTRIA => 'النمسا',
                self::AZERBAIJAN => 'أذربيجان',
                self::BAHAMAS => 'البهاما',
                self::BAHRAIN => 'البحرين',
                self::BANGLADESH => 'بنغلاديش',
                self::BARBADOS => 'بربادوس',
                self::BELARUS => 'بيلاروسيا',
                self::BELGIUM => 'بلجيكا',
                self::BELIZE => 'بليز',
                self::BENIN => 'بنين',
                self::BHUTAN => 'بوتان',
                self::BOLIVIA => 'بوليفيا',
                self::BOSNIA_AND_HERZEGOVINA => 'البوسنة والهرسك',
                self::BOTSWANA => 'بوتسوانا',
                self::BRAZIL => 'البرازيل',
                self::BRUNEI => 'بروناي',
                self::BULGARIA => 'بلغاريا',
                self::BURKINA_FASO => 'بوركينا فاسو',
                self::BURUNDI => 'بوروندي',
                self::CAMBODIA => 'كمبوديا',
                self::CAMEROON => 'الكاميرون',
                self::CANADA => 'كندا',
                self::CAPE_VERDE => 'الرأس الأخضر',
                self::CENTRAL_AFRICAN_REPUBLIC => 'جمهورية أفريقيا الوسطى',
                self::CHAD => 'تشاد',
                self::CHILE => 'تشيلي',
                self::CHINA => 'الصين',
                self::COLOMBIA => 'كولومبيا',
                self::COMOROS => 'جزر القمر',
                self::CONGO => 'الكونغو',
                self::COSTA_RICA => 'كوستاريكا',
                self::CROATIA => 'كرواتيا',
                self::CUBA => 'كوبا',
                self::CYPRUS => 'قبرص',
                self::CZECHIA => 'التشيك',
                self::DENMARK => 'الدنمارك',
                self::DJIBOUTI => 'جيبوتي',
                self::DOMINICA => 'دومينيكا',
                self::ECUADOR => 'الإكوادور',
                self::EGYPT => 'مصر',
                self::EL_SALVADOR => 'السلفادور',
                self::ESTONIA => 'إستونيا',
                self::ETHIOPIA => 'إثيوبيا',
                self::FIJI => 'فيجي',
                self::FINLAND => 'فنلندا',
                self::FRANCE => 'فرنسا',
                self::GERMANY => 'ألمانيا',
                self::GHANA => 'غانا',
                self::GREECE => 'اليونان',
                self::GUATEMALA => 'غواتيمالا',
                self::HAITI => 'هايتي',
                self::HONDURAS => 'هندوراس',
                self::HUNGARY => 'هنغاريا',
                self::ICELAND => 'آيسلندا',
                self::INDIA => 'الهند',
                self::INDONESIA => 'إندونيسيا',
                self::IRAN => 'إيران',
                self::IRAQ => 'العراق',
                self::IRELAND => 'أيرلندا',
                self::ISRAEL => 'إسرائيل',
                self::ITALY => 'إيطاليا',
                self::JAMAICA => 'جامايكا',
                self::JAPAN => 'اليابان',
                self::JORDAN => 'الأردن',
                self::KAZAKHSTAN => 'كازاخستان',
                self::KENYA => 'كينيا',
                self::KUWAIT => 'الكويت',
                self::LATVIA => 'لاتفيا',
                self::LEBANON => 'لبنان',
                self::LIBYA => 'ليبيا',
                self::LUXEMBOURG => 'لوكسمبورغ',
                self::MADAGASCAR => 'مدغشقر',
                self::MALAYSIA => 'ماليزيا',
                self::MEXICO => 'المكسيك',
                self::MOROCCO => 'المغرب',
                self::NETHERLANDS => 'هولندا',
                self::NEW_ZEALAND => 'نيوزيلندا',
                self::NIGERIA => 'نيجيريا',
                self::NORWAY => 'النرويج',
                self::PAKISTAN => 'باكستان',
                self::PERU => 'بيرو',
                self::PHILIPPINES => 'الفلبين',
                self::POLAND => 'بولندا',
                self::PORTUGAL => 'البرتغال',
                self::QATAR => 'قطر',
                self::ROMANIA => 'رومانيا',
                self::RUSSIA => 'روسيا',
                self::SAUDI_ARABIA => 'السعودية',
                self::SINGAPORE => 'سنغافورة',
                self::SOUTH_AFRICA => 'جنوب أفريقيا',
                self::SOUTH_KOREA => 'كوريا الجنوبية',
                self::SPAIN => 'إسبانيا',
                self::SRI_LANKA => 'سريلانكا',
                self::SWEDEN => 'السويد',
                self::SWITZERLAND => 'سويسرا',
                self::THAILAND => 'تايلاند',
                self::TUNISIA => 'تونس',
                self::TURKEY => 'تركيا',
                self::UAE => 'الإمارات',
                self::UK => 'المملكة المتحدة',
                self::UKRAINE => 'أوكرانيا',
                self::USA => 'الولايات المتحدة',
                self::VIETNAM => 'فيتنام',
                self::ZIMBABWE => 'زيمبابوي',
            },
        ], self::cases());
    }
}
