<?php

namespace App\Enums;

enum CurrencyType: string
{
    case SAR = 'SAR';
    case AED = 'AED';
    case USD = 'USD';
    case EUR = 'EUR';
    case CAD = 'CAD';
    case AFN = 'AFN';
    case ALL = 'ALL';
    case AMD = 'AMD';
    case ARS = 'ARS';
    case AUD = 'AUD';
    case AZN = 'AZN';
    case BAM = 'BAM';
    case BDT = 'BDT';
    case BGN = 'BGN';
    case BHD = 'BHD';
    case BIF = 'BIF';
    case BND = 'BND';
    case BOB = 'BOB';
    case BRL = 'BRL';
    case BWP = 'BWP';
    case BYN = 'BYN';
    case BZD = 'BZD';
    case CDF = 'CDF';
    case CHF = 'CHF';
    case CLP = 'CLP';
    case CNY = 'CNY';
    case COP = 'COP';
    case CRC = 'CRC';
    case CVE = 'CVE';
    case CZK = 'CZK';
    case DJF = 'DJF';
    case DKK = 'DKK';
    case DOP = 'DOP';
    case DZD = 'DZD';
    case EGP = 'EGP';
    case ERN = 'ERN';
    case ETB = 'ETB';
    case GBP = 'GBP';
    case GEL = 'GEL';
    case GHS = 'GHS';
    case GNF = 'GNF';
    case GTQ = 'GTQ';
    case HKD = 'HKD';
    case HNL = 'HNL';
    case HRK = 'HRK';
    case HUF = 'HUF';
    case IDR = 'IDR';
    case ILS = 'ILS';
    case INR = 'INR';
    case IQD = 'IQD';
    case IRR = 'IRR';
    case ISK = 'ISK';
    case JMD = 'JMD';
    case JOD = 'JOD';
    case JPY = 'JPY';
    case KES = 'KES';
    case KHR = 'KHR';
    case KMF = 'KMF';
    case KRW = 'KRW';
    case KWD = 'KWD';
    case KZT = 'KZT';
    case LBP = 'LBP';
    case LKR = 'LKR';
    case LYD = 'LYD';
    case MAD = 'MAD';
    case MDL = 'MDL';
    case MGA = 'MGA';
    case MKD = 'MKD';
    case MMK = 'MMK';
    case MOP = 'MOP';
    case MUR = 'MUR';
    case MXN = 'MXN';
    case MYR = 'MYR';
    case MZN = 'MZN';
    case NAD = 'NAD';
    case NGN = 'NGN';
    case NIO = 'NIO';
    case NOK = 'NOK';
    case NPR = 'NPR';
    case NZD = 'NZD';
    case OMR = 'OMR';
    case PAB = 'PAB';
    case PEN = 'PEN';
    case PHP = 'PHP';
    case PKR = 'PKR';
    case PLN = 'PLN';
    case PYG = 'PYG';
    case QAR = 'QAR';
    case RON = 'RON';
    case RSD = 'RSD';
    case RUB = 'RUB';
    case RWF = 'RWF';
    case SDG = 'SDG';
    case SEK = 'SEK';
    case SGD = 'SGD';
    case SOS = 'SOS';
    case SYP = 'SYP';
    case THB = 'THB';
    case TND = 'TND';
    case TOP = 'TOP';
    case TRY = 'TRY';
    case TTD = 'TTD';
    case TWD = 'TWD';
    case TZS = 'TZS';
    case UAH = 'UAH';
    case UGX = 'UGX';
    case UYU = 'UYU';
    case UZS = 'UZS';
    case VES = 'VES';
    case VND = 'VND';
    case XAF = 'XAF';
    case XOF = 'XOF';
    case YER = 'YER';
    case ZAR = 'ZAR';
    case ZMW = 'ZMW';

    public static function options(): array
    {
        return array_map(fn(self $currency) => [
            'value' => $currency->value,
            'label' => match ($currency) {
                self::SAR => 'ريال سعودي',
                self::AED => 'درهم إماراتي',
                self::USD => 'دولار أمريكي',
                self::EUR => 'يورو',
                self::CAD => 'دولار كندي',
                self::AFN => 'أفغاني',
                self::ALL => 'ليك ألباني',
                self::AMD => 'درام أرميني',
                self::ARS => 'بيزو أرجنتيني',
                self::AUD => 'دولار أسترالي',
                self::AZN => 'مانات أذربيجاني',
                self::BAM => 'مارك البوسنة والهرسك',
                self::BDT => 'تاكا بنغلاديشي',
                self::BGN => 'ليف بلغاري',
                self::BHD => 'دينار بحريني',
                self::BIF => 'فرنك بوروندي',
                self::BND => 'دولار بروناي',
                self::BOB => 'بوليفيانو بوليفي',
                self::BRL => 'ريال برازيلي',
                self::BWP => 'بولا بوتسواني',
                self::BYN => 'روبل بيلاروسي',
                self::BZD => 'دولار بليزي',
                self::CDF => 'فرنك كونغولي',
                self::CHF => 'فرنك سويسري',
                self::CLP => 'بيزو تشيلي',
                self::CNY => 'يوان صيني',
                self::COP => 'بيزو كولومبي',
                self::CRC => 'كولون كوستاريكي',
                self::CVE => 'اسكودو الرأس الأخضر',
                self::CZK => 'كورونا تشيكية',
                self::DJF => 'فرنك جيبوتي',
                self::DKK => 'كرونة دنماركية',
                self::DOP => 'بيزو الدومينيكان',
                self::DZD => 'دينار جزائري',
                self::EGP => 'جنيه مصري',
                self::ERN => 'ناكفا إريتري',
                self::ETB => 'بير إثيوبي',
                self::GBP => 'جنيه إسترليني',
                self::GEL => 'لاري جورجي',
                self::GHS => 'سيدي غاني',
                self::GNF => 'فرنك غيني',
                self::GTQ => 'كتزال غواتيمالي',
                self::HKD => 'دولار هونغ كونغ',
                self::HNL => 'لمبيرا هندوراسية',
                self::HRK => 'كونا كرواتية',
                self::HUF => 'فورنت مجري',
                self::IDR => 'روبية إندونيسية',
                self::ILS => 'شيكل إسرائيلي',
                self::INR => 'روبية هندية',
                self::IQD => 'دينار عراقي',
                self::IRR => 'ريال إيراني',
                self::ISK => 'كرونة آيسلندية',
                self::JMD => 'دولار جامايكي',
                self::JOD => 'دينار أردني',
                self::JPY => 'ين ياباني',
                self::KES => 'شلن كيني',
                self::KHR => 'ريال كمبودي',
                self::KMF => 'فرنك قمري',
                self::KRW => 'وون كوري',
                self::KWD => 'دينار كويتي',
                self::KZT => 'تينغ كازاخستاني',
                self::LBP => 'ليرة لبنانية',
                self::LKR => 'روبية سريلانكية',
                self::LYD => 'دينار ليبي',
                self::MAD => 'درهم مغربي',
                self::MDL => 'ليو مولدوفي',
                self::MGA => 'أرياري ملغاشي',
                self::MKD => 'دينار مقدوني',
                self::MMK => 'كيات ميانماري',
                self::MOP => 'باتاكا ماكاوي',
                self::MUR => 'روبية موريشيوسية',
                self::MXN => 'بيزو مكسيكي',
                self::MYR => 'رينغيت ماليزي',
                self::MZN => 'ميتيكال موزمبيقي',
                self::NAD => 'دولار ناميبي',
                self::NGN => 'نايرا نيجيري',
                self::NIO => 'كوردوبا نيكاراغوي',
                self::NOK => 'كرونة نرويجية',
                self::NPR => 'روبية نيبالية',
                self::NZD => 'دولار نيوزيلندي',
                self::OMR => 'ريال عماني',
                self::PAB => 'بالبوا بنمي',
                self::PEN => 'سول بيروفي',
                self::PHP => 'بيزو فلبيني',
                self::PKR => 'روبية باكستانية',
                self::PLN => 'زلوتي بولندي',
                self::PYG => 'غواراني باراغواي',
                self::QAR => 'ريال قطري',
                self::RON => 'ليو روماني',
                self::RSD => 'دينار صربي',
                self::RUB => 'روبل روسي',
                self::RWF => 'فرنك رواندي',
                self::SDG => 'جنيه سوداني',
                self::SEK => 'كرونة سويدية',
                self::SGD => 'دولار سنغافوري',
                self::SOS => 'شلن صومالي',
                self::SYP => 'ليرة سورية',
                self::THB => 'بات تايلاندي',
                self::TND => 'دينار تونسي',
                self::TOP => 'بانغا تونغي',
                self::TRY => 'ليرة تركية',
                self::TTD => 'دولار ترينيدادي',
                self::TWD => 'دولار تايواني',
                self::TZS => 'شلن تنزاني',
                self::UAH => 'هريفنيا أوكرانية',
                self::UGX => 'شلن أوغندي',
                self::UYU => 'بيزو أوروغواي',
                self::UZS => 'سوم أوزبكي',
                self::VES => 'بوليفار فنزويلي',
                self::VND => 'دونغ فيتنامي',
                self::XAF => 'فرنك إفريقي وسط',
                self::XOF => 'فرنك إفريقي غربي',
                self::YER => 'ريال يمني',
                self::ZAR => 'راند جنوب أفريقي',
                self::ZMW => 'كواشا زامبي'
            }
        ], self::cases());
    }
}
